# ====== Usuall default
seed = 10086

# ========= Model related
n_dims = 20
gpt_type = "standard"

# ========= Task related 
prompt_points = 101
task = "LR"

# ========= Training
curr_interval = 1000
curr_dim_start = 5
curr_points_start = 20
train_steps = 500001
lr = 0.0001
b_size = 64


save_model = true
save_every_steps = 500001
proj_name = "P5_iICL_toy"
run_name = "LR_try"